version: '3.2'
services:
  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - PGID=${GID}
      - PUID=${UID}
      - AB_INTERVAL_TIME=1800
      - AB_DOWNLOADER_HOST=localhost:${QB_PORT}
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_METHOD=pn
      - AB_GROUP_TAG=True
      - AB_NOT_CONTAIN=720
      - AB_DOWNLOAD_PATH=${DOWNLOAD_PATH}
      - AB_RSS=${RSS}
      - AB_DEBUG_MODE=False
      - AB_EP_COMPLETE=False
      - AB_SEASON_ONE=True
    networks:
      - auto_bangumi
    ports:
      - 7892:7892
    volumes:
      - auto_bangumi:/config
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest

networks:
  auto_bangumi:
volumes:
  auto_bangumi:
    external: false
