version: "3.2"
services:
  qbittorrent:
    container_name: qBittorrent
    environment:
      - TZ=Asia/Shanghai
      - TemPath=/downloads
      - SavePath=/downloads
      - PGID=${GID}
      - PUID=${UID}
      - WEBUI_PORT=${QB_PORT}
    volumes:
      - qb_config:/config
      - ${DOWNLOAD_PATH}:/downloads # 填入下载绝对路径
    ports:
      - ${QB_PORT}:${QB_PORT}
      - 6881:6881
      - 6881:6881/udp
    networks:
      - auto_bangumi
    restart: unless-stopped
    image: lscr.io/linuxserver/qbittorrent:4.4.3

  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - PGID=${GID}
      - PUID=${UID}
      - AB_DOWNLOADER_HOST=qbittorrent:${QB_PORT}
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_DOWNLOAD_PATH=/downloads/Bangumi
      - AB_RSS=${RSS}
    volumes:
      - auto_bangumi:/config
    networks:
      - /path/to/config:/app/config
      - /path/to/data:/app/data
    ports:
      - 7892:7892
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest
    depends_on:
      - qbittorrent

networks:
  auto_bangumi:
volumes:
  qb_config:
    external: false
