version: "3.2"
services:
  qbittorrent:
    container_name: qBittorrent
    environment:
      - TZ=Asia/Shanghai
      - TemPath=/downloads
      - SavePath=/downloads
      - PGID=${GID}
      - PUID=${UID}
      - WEBUI_PORT=${QB_PORT}
    volumes:
      - qb_config:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - ${QB_PORT}:${QB_PORT}
      - 6881:6881
      - 6881:6881/udp
    networks:
      - auto_bangumi
    restart: unless-stopped
    image: lscr.io/linuxserver/qbittorrent:4.4.3

  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - AB_INTERVAL_TIME=1800
      - AB_DOWNLOADER_HOST=qbittorrent:${QB_PORT}
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_METHOD=pn
      - AB_GROUP_TAG=True
      - AB_NOT_CONTAIN=720
      - AB_DOWNLOAD_PATH=/downloads/Bangumi
      - AB_RSS=${RSS}
      - AB_DEBUG_MODE=False
      - AB_EP_COMPLETE=False
      - AB_SEASON_ONE=True
    networks:
      - auto_bangumi
    volumes:
      - auto_bangumi:/config
    ports:
      - 7892:7892
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest
    depends_on:
      - qbittorrent

  plex:
    container_name: Plex
    environment:
      - TZ=Asia/Shanghai
      - PUID=${UID}
      - PGID=${GID}
      - VERSION=docker
    networks:
      - auto_bangumi
    ports:
      - 32400:32400
    volumes:
      - plex_config:/config
      - ${DOWNLOAD_PATH}/Bangumi:/tv
    restart: unless-stopped
    image: lscr.io/linuxserver/plex:latest

networks:
  auto_bangumi:

volumes:
  qb_config:
    external: false
  plex_config:
    external: false
  auto_bangumi:
    external: false

